// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package entity

func (s *Posts) MapInt64(fc func(something *Post) int64) []int64 {
	results := make([]int64, len(*s))
	for i, something := range *s {
		results[i] = fc(&something)
	}
	return results
}

func (s *Posts) GroupByInt64(fc func(something *Post) int64) map[int64]Post {
	results := make(map[int64]Post, len(*s))
	for _, something := range *s {
		results[fc(&something)] = something
	}
	return results
}

func (s *Posts) MapPostUser(fc func(something *Post) PostUser) []PostUser {
	results := make([]PostUser, len(*s))
	for i, something := range *s {
		results[i] = fc(&something)
	}
	return results
}

func (s *Posts) GroupByPostUser(fc func(something *Post) PostUser) map[PostUser]Post {
	results := make(map[PostUser]Post, len(*s))
	for _, something := range *s {
		results[fc(&something)] = something
	}
	return results
}
