// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package entity

func (s *PostUsers) MapInterface(fc func(something *PostUser) interface{}) []interface{} {
	results := make([]interface{}, len(*s))
	for i, something := range *s {
		results[i] = fc(&something)
	}
	return results
}

func (s *PostUsers) GroupByInterface(fc func(something *PostUser) interface{}) map[interface{}]PostUser {
	results := make(map[interface{}]PostUser, len(*s))
	for _, something := range *s {
		results[fc(&something)] = something
	}
	return results
}
