// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package entity

func (s *Users) MapInt64(fc func(something *User) int64) []int64 {
	results := make([]int64, len(*s))
	for i, something := range *s {
		results[i] = fc(&something)
	}
	return results
}

func (s *Users) GroupByInt64(fc func(something *User) int64) map[int64]User {
	results := make(map[int64]User, len(*s))
	for _, something := range *s {
		results[fc(&something)] = something
	}
	return results
}
