service: greddit-server
#app: your-app-name
org: duyike

frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin # can read .env without settings

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-northeast-1
  environment:
    PORT: ${env.PORT}
    UID_COOKIE_NAME: ${env.UID_COOKIE_NAME}
    UID_HTTP_KEY: ${env.UID_HTTP_KEY}

# Lambda function's IAM Role
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  api:
    handler: bin/lambda
    events:
      - http:
          path: /{proxy+}
          method: ANY