// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HasMore interface {
	IsHasMore()
	GetHasMore() bool
}

type CreatePost struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}

type EmailLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type HasMorePosts struct {
	HasMore bool    `json:"hasMore"`
	List    []*Post `json:"list"`
}

func (HasMorePosts) IsHasMore()            {}
func (this HasMorePosts) GetHasMore() bool { return this.HasMore }

type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type Post struct {
	PostID     int64  `json:"postId"`
	CreatorUID int64  `json:"creatorUid"`
	Title      string `json:"title"`
	Text       string `json:"text"`
	VoteCount  int64  `json:"voteCount"`
	Creator    *User  `json:"creator"`
}

type Register struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Token struct {
	Token string `json:"token"`
}

type User struct {
	UID      int64   `json:"uid"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password *string `json:"password"`
}

type UsernameLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
