package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"go.uber.org/zap"

	"github.com/duyike/greddit/internal/graphql/graph"
	"github.com/duyike/greddit/internal/graphql/graph/dataloader"
	"github.com/duyike/greddit/internal/graphql/graph/model"
)

// Creator is the resolver for the creator field.
func (r *postResolver) Creator(ctx context.Context, obj *model.Post) (*model.User, error) {
	return dataloader.For(ctx).GetUser(ctx, obj.CreatorUID)
}

// Post returns graph.PostResolver implementation.
func (r *Resolver) Post() graph.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
var (
	_, _ = zap.NewProduction(zap.Fields(zap.String("type", "resolver")))
)
