// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package post

func (s *Posts) MapInt64(fc func(something *Post) int64) []int64 {
	results := make([]int64, len(*s))
	for i, something := range *s {
		results[i] = fc(&something)
	}
	return results
}

func (s *Posts) GroupByInt64(fc func(something *Post) int64) map[int64]Post {
	results := make(map[int64]Post, len(*s))
	for _, something := range *s {
		results[fc(&something)] = something
	}
	return results
}

func (s *Posts) MapWithUser(fc func(something *Post) WithUser) []WithUser {
	results := make([]WithUser, len(*s))
	for i, something := range *s {
		results[i] = fc(&something)
	}
	return results
}

func (s *Posts) GroupByWithUser(fc func(something *Post) WithUser) map[WithUser]Post {
	results := make(map[WithUser]Post, len(*s))
	for _, something := range *s {
		results[fc(&something)] = something
	}
	return results
}
