name: Deploy main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.8.1
      - name: Setup serverless framework
        uses: Teakowa/setup-serverless@v2.0.0
        with:
          provider: aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Install serverless dotenv plugin
        run: sls plugin install -n serverless-dotenv-plugin
      - name: Deploy
        run: make deploy
        env:
          DEPLOYMENT: PRODUCTION
          PORT: 8080
          UID_COOKIE_NAME: user_id
          UID_HTTP_KEY: uid
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}